phrase:
  host: https://api.us.app.phrase.com/v2
  access_token: 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
  project_id: a1f4202162d6aef2fcf9c83d4ff56672
  push:
    sources:
    - file: ./src/assets/i18n/en.json
      params:
        file_format: i18next
        locale_id: en
        tags: REVIEW_NEEDED
  pull:
    targets:
    - file: ./src/assets/i18n/en.json
      params:
        file_format: i18next
        locale_id: en
